import { ListItem } from "./types";

export const RecurringListItems: ListItem[] = [
  {
    listID: "",
    itemID: "",
    label: "Milk",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Dairy",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Eggs",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Dairy",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Bread",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Bakery",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Butter",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Dairy",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Cheese",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Dairy",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Chicken",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Meat & Poultry",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Ground Beef",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Meat & Poultry",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Lettuce",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Tomatoes",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Cucumbers",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Apples",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Bananas",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Oranges",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Potatoes",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Onions",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Produce",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Rice",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Canned Goods",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Pasta",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Canned Goods",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Cereal",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Breakfast Foods",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Yogurt",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Dairy",
    posterID: "",
  },
  {
    listID: "",
    itemID: "",
    label: "Toilet Paper",
    isRecurring: true,
    amount: 1,
    checked: false,
    description: "",
    categoryID: "Household Essentials",
    posterID: "",
  },
];
